# Data paths
data: "data"

captions_train: "captions_train.csv"
captions_val: "captions_val.csv"

train: "data/YOLO_format/train"
val: "data/YOLO_format/valid"
test: "data/YOLO_format/test"

#train_full: "/mnt/scratch/users/adgs896/affectnet_upload/train_set"
#val_full: "/mnt/scratch/users/adgs896/affectnet_upload/val_set"
#test_full: "/mnt/scratch/users/adgs896/affectnet_upload/test_set"

train_full: "data/full_data/train_set"
val_full: "data/full_data/val_set"
test_full: "data/full_data/test_set"

# Model parameters
image_size: 256
batch_size: 256
num_workers: 4
num_classes: 8

# Optimized Training parameters
num_epochs: 30
learning_rate: 0.00001         # Lower LR = slower, more stable learning (less overfitting)
weight_decay: 0.05          # Stronger regularization to penalize overly complex models
scheduler_step_size: 3      # Decay learning rate more frequently
scheduler_gamma: 0.3        # Decay it more aggressively when triggered

# Output settings
checkpoint_dir: 'checkpoints'
output_dir: 'outputs/visualizations'
viz_frequency: 2  # Save visualization every N epochs

# Custom Loss
alpha: 0.1