# Data paths
img_dir: './dataset'
RAF_DB_img_dir_train: './dataset/train_labels.csv'
RAF_DB_img_dir_test: './dataset/test_labels.csv'


# Model parameters
image_size: 256
batch_size: 8
num_workers: 4

# Optimized Training parameters
num_epochs: 30
learning_rate: 1e-4
weight_decay: 0.02
scheduler_step_size: 5
scheduler_gamma: 0.5

# Output settings
checkpoint_dir: 'checkpoints'
output_dir: 'outputs/visualizations'
viz_frequency: 2  # Save visualization every N epochs

# Custom Loss
alpha: 0.1